In [ ]:
import torch
import numpy as np


In [70]:
unbiased_train_shift = torch.load("./best_shift_fourier4.pt")
biased_train_shift = torch.load("./biased_best_state2.pt")
unbiased_test_shift = torch.load("./unbiased_test_shift.pt")
biased_test_shift = torch.load("./biased_test_shift.pt")

Splines_unbiased_train_shift = torch.load("./Splines_beststate_0")
Splines_unbiased_test_shift = torch.load("./Splines_testalign_0")

In [71]:
n_structures = 1039
np.random.seed(0)
n_train = int(0.8 * n_structures)
train_index = np.arange(n_structures)
np.random.shuffle(train_index)
test_index = train_index[n_train:]
train_index = train_index[:n_train]

#Selected Amorphous structures

amorph_train = np.arange(939,1039,1)
np.random.seed(0)
np.random.shuffle(amorph_train)

amorph_test = amorph_train[:80]
amorph_train = amorph_train[80:]

n_structures2 = 939
np.random.seed(0)
n_train = int(0.8 * 1039)-20
remaining_train_index = np.arange(n_structures2)
np.random.shuffle(remaining_train_index)

remaining_test_index = remaining_train_index[n_train:]
remaining_train_index = remaining_train_index[:n_train]

biased_train_index = np.concatenate([remaining_train_index, amorph_train])
biased_test_index = np.concatenate([remaining_test_index, amorph_test])

In [72]:
unbiased_shifts = torch.zeros(n_structures).double()
biased_shifts = torch.zeros(n_structures).double()


unbiased_shifts.index_add_(dim = 0, index = torch.tensor(train_index), source = Splines_unbiased_train_shift)
unbiased_shifts.index_add_(dim = 0, index = torch.tensor(test_index), source = Splines_unbiased_test_shift)

biased_shifts.index_add_(dim = 0, index = torch.tensor(biased_train_index), source = biased_train_shift)
biased_shifts.index_add_(dim = 0, index = torch.tensor(biased_test_index), source = biased_test_shift)


tensor([0.1585, 0.1279, 0.1512,  ..., 0.0969, 0.0829, 0.1146],
       dtype=torch.float64, grad_fn=<IndexAddBackward0>)

In [73]:
torch.mean((biased_shifts - unbiased_shifts)**2)

tensor(0.1330, dtype=torch.float64, grad_fn=<MeanBackward0>)

In [74]:
diamond_range = np.arange(0,324,1)
beta_tin_range = np.arange(324,604,1)
liquid_range = np.arange(604, 673, 1)
clusters_range = np.arange(673, 939, 1)
amorphous_range = np.arange(939, 1039, 1)

unbiased_shifts: -0.6 to 0.8 eV

In [75]:
(unbiased_shifts - unbiased_shifts[0])[diamond_range]

tensor([ 0.0000,  0.0973, -0.0184,  0.1250,  0.1443,  0.2085,  0.1924, -0.0480,
        -0.0504,  0.1583, -0.1064,  0.1510, -0.1830,  0.0981,  0.2057,  0.1705,
        -0.1820,  0.1238,  0.0298, -0.1703, -0.3380, -0.0686,  0.1340, -0.0990,
        -0.0794, -0.0879, -0.2865,  0.0527,  0.0015, -0.2265, -0.2175, -0.1670,
        -0.1110, -0.2800, -0.1070, -0.1050, -0.1931, -0.1930, -0.1950, -0.2120,
        -0.3101, -0.2689, -0.3260, -0.2941, -0.1750, -0.4440, -0.3370, -0.4260,
        -0.4211, -0.4022, -0.2660, -0.5830, -0.3200, -0.1870, -0.3134, -0.4310,
        -0.4706, -0.5270, -0.2682, -0.4200, -0.4994, -0.2420, -0.4470, -0.4736,
        -0.7490, -0.5490, -0.5120, -0.4910, -0.5155, -0.5180, -0.3950, -0.5740,
        -0.4930, -0.5150, -0.5701, -0.3422, -0.3710, -0.4851, -0.7306, -0.7716,
        -0.6365, -0.6280, -0.4050, -0.5206, -0.5180, -0.6491, -0.5400, -0.6890,
        -0.6916, -0.7110, -0.7283, -0.6601, -0.7420, -0.7570, -0.6916, -0.4986,
        -0.9546, -0.5940, -0.7179, -0.89

In [77]:
print (torch.min((unbiased_shifts - biased_shifts[0])[diamond_range]))
print (torch.max((unbiased_shifts - biased_shifts[0])[diamond_range]))

tensor(-0.8853, dtype=torch.float64, grad_fn=<MinBackward1>)
tensor(0.2778, dtype=torch.float64, grad_fn=<MaxBackward1>)


In [ ]:
(unbiased_shifts - unbiased_shifts[0])[beta_tin_range]

-0.7308 to 0.6845 eV

In [ ]:
(unbiased_shifts - unbiased_shifts[0])[liquid_range]

-0.5366eV to 0.2740eV

In [ ]:
(unbiased_shifts - unbiased_shifts[0])[clusters_range]

-0.6639 to 0.0285eV

In [ ]:
(unbiased_shifts - unbiased_shifts[0])[amorphous_range]

-0.3872 to -0.1448 eV

In [ ]:
(biased_shifts - biased_shifts[0])[diamond_range]

In [22]:
biased_shifts - biased_shifts[0]

tensor([ 0.0000, -0.0306, -0.0073,  ..., -0.0616, -0.0756, -0.0439],
       dtype=torch.float64, grad_fn=<SubBackward0>)

In [28]:
torch.min(torch.rand(1039)-0.5)

tensor(-0.4958)

In [76]:
print (torch.min((biased_shifts - biased_shifts[0])[diamond_range]))
print (torch.max((biased_shifts - biased_shifts[0])[diamond_range]))

tensor(-0.6878, dtype=torch.float64, grad_fn=<MinBackward1>)
tensor(0.4840, dtype=torch.float64, grad_fn=<MaxBackward1>)


In [ ]:
(biased_shifts - biased_shifts[0])[beta_tin_range]

In [61]:
print (torch.min((biased_shifts - biased_shifts[0])[beta_tin_range]))
print (torch.max((biased_shifts - biased_shifts[0])[beta_tin_range]))

tensor(-0.9028, dtype=torch.float64, grad_fn=<MinBackward1>)
tensor(0.5133, dtype=torch.float64, grad_fn=<MaxBackward1>)


In [ ]:
(biased_shifts - biased_shifts[0])[liquid_range]

In [62]:
print (torch.min((biased_shifts - biased_shifts[0])[liquid_range]))
print (torch.max((biased_shifts - biased_shifts[0])[liquid_range]))

tensor(-0.6415, dtype=torch.float64, grad_fn=<MinBackward1>)
tensor(0.2849, dtype=torch.float64, grad_fn=<MaxBackward1>)


In [ ]:
(biased_shifts - biased_shifts[0])[clusters_range]

In [63]:
print (torch.min((biased_shifts - biased_shifts[0])[clusters_range]))
print (torch.max((biased_shifts - biased_shifts[0])[clusters_range]))

tensor(-0.6925, dtype=torch.float64, grad_fn=<MinBackward1>)
tensor(0.0377, dtype=torch.float64, grad_fn=<MaxBackward1>)


In [ ]:
(biased_shifts - biased_shifts[0])[amorphous_range]

In [64]:
print (torch.min((biased_shifts - biased_shifts[0])[amorphous_range]))
print (torch.max((biased_shifts - biased_shifts[0])[amorphous_range]))

tensor(-0.3329, dtype=torch.float64, grad_fn=<MinBackward1>)
tensor(-0.0102, dtype=torch.float64, grad_fn=<MaxBackward1>)
