In [1]:
import os
import torch
import numpy as np
import json
import ase
import ase.io
import dostools.datasets.data as data

In [7]:
with torch.no_grad():
    surface_structures = ase.io.read("./surfaces.xyz", ":")
    bulk_structures = data.load_structures(":")
    total_structures = bulk_structures[:673] + surface_structures + bulk_structures[939:]
    n_structures = len(total_structures) #total number of structures
    for structure in structures:#implement periodicity
        structure.wrap(eps = 1e-12) 
    n_atoms = np.zeros(n_structures, dtype = int) #stores number of atoms in each structures
    for i in range(n_structures):
        n_atoms[i] = len(total_structures[i])
        
    

hi


In [131]:
total_structures[673:673+154]

[Atoms(symbols='Si96', pbc=[True, True, False], cell=[15.361142576428, 15.361142576428, 60.0000002590845]),
 Atoms(symbols='Si160', pbc=[True, True, False], cell=[15.361142576428, 15.361142576428, 70.0000003886267]),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.35000126, 60.900001610000004], dft_force=...),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.35000126, 60.900001610000004], dft_force=...),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.35000126, 60.900001610000004], dft_force=...),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.35000126, 60.900001610000004], dft_force=...),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.35000126, 60.900001610000004], dft_force=...),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.35000126, 60.900001610000004], dft_force=...),
 Atoms(symbols='Si144', pbc=[True, True, False], cell=[16.35000126, 16.3500

In [129]:
len(total_structures)

927

In [11]:
ase.io.write("total_structures.xyz", total_structures)

In [62]:
eigen_energies, emin, emax = data.load_eigenenergies(unpack = True, n_structures = 1039)
full_eigen_energies = [torch.tensor(i.flatten()) for i in eigen_energies]
eigenenergy_length = [len(i) for i in full_eigen_energies]
eigenenergy_length_t = torch.tensor(eigenenergy_length)
normalization_eiglength = [len(i) for i in eigen_energies]
normalization_eiglength_t = torch.tensor(normalization_eiglength)
# normalization = 1/torch.sqrt(2*torch.tensor(np.pi)*sigma**2)/n_atoms/normalization_eiglength_t
# normalization_quartic = 1/n_atoms/normalization_eiglength_t

This file contains the eigenenergies and their corresponding kpoints of the training Silicon structures generated using DFT PBE as implemented in FHI-AIMS version 171221_1 with the ``tight'' settings


RuntimeError: The size of tensor a (927) must match the size of tensor b (1039) at non-singleton dimension 0

In [65]:
bulk_eigen_energies = eigen_energies.copy()

In [63]:
len(eigen_energies)

1039

In [32]:
f = open("./eigenenergies.json")
surfaces_eigen_energies = json.load(f)

t_surfaces_eigen_energies = [torch.tensor(surfaces_eigen_energies[i]) for i in surfaces_eigen_energies]
k_normalization = torch.tensor([len(i) for i in t_surfaces_eigen_energies])
t_surfaces_eigen_energies = [i[i>-70] for i in t_surfaces_eigen_energies]
normalization_surface = 1/torch.sqrt(2*torch.tensor(np.pi)*sigma**2)/n_atoms/k_normalization

In [33]:
surface_eigen_energies = []
for i in surfaces_eigen_energies:
    surface_eigen_energies.append(np.array(surfaces_eigen_energies[i]))
    

In [43]:
k_normalization

tensor([64, 64, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
        49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 70, 70, 70, 70, 70,
        70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
        70, 70, 70, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54,
        54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54,
        54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 72, 72, 72, 72,
        72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
        72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
        72, 72, 72, 72, 72, 72, 72, 72, 72, 72])

In [41]:
full_eigen_energies = [torch.tensor(i.flatten()) for i in total_eigen_energies]
eigenenergy_length = [len(i) for i in full_eigen_energies]
eigenenergy_length_t = torch.tensor(eigenenergy_length)
normalization_eiglength = [len(i) for i in total_eigen_energies]
normalization_eiglength_t = torch.tensor(normalization_eiglength)
normalization = 1/torch.sqrt(2*torch.tensor(np.pi)*sigma**2)/n_atoms/normalization_eiglength_t
# normalization_quartic = 1/n_atoms/normalization_eiglength_t

RuntimeError: The size of tensor a (927) must match the size of tensor b (827) at non-singleton dimension 0

In [122]:
total_eigen_energies_list = bulk_eigen_energies[:673] + surface_eigen_energies + bulk_eigen_energies[939:]
total_eigen_energies = [torch.tensor(i).flatten() for i in total_eigen_energies_list]
total_eigen_energies = [i[i>-70] for i in total_eigen_energies]

emin = torch.min(torch.tensor([torch.min(i) for i in total_eigen_energies]))
emax = torch.max(torch.tensor([torch.max(i) for i in total_eigen_energies]))

normalization_eiglength = [len(i) for i in total_eigen_energies_list]
normalization_eiglength_t = torch.tensor(normalization_eiglength)
normalization = 1/torch.sqrt(2*torch.tensor(np.pi)*sigma**2)/n_atoms/normalization_eiglength_t

In [123]:
emin

tensor(-24.5537, dtype=torch.float64)

In [127]:
normalization

tensor([0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0003, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0003, 0.0004, 0.0004, 0.0004, 0.0003, 0.0004, 0.0003, 0.0003, 0.0004,
        0.0003, 0.0003, 0.0004, 0.0004, 0.0004, 0.0004, 0.0004, 0.0003, 0.0004,
        0.0003, 0.0004, 0.0004, 0.0004, 0.0003, 0.0003, 0.0004, 0.0004, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0003, 0.0003, 0.0004, 0.0003, 0.0003, 0.0003,
        0.0003, 0.0003, 0.0003, 0.0004, 0.0003, 0.0004, 0.0004, 0.0004, 0.0004,
        0.0004, 0.0004, 0.0004, 0.0004, 

In [110]:
emax

12.8464

In [121]:
sigma = 0.3

In [115]:
sigma = 0.1
normalization1 = 1/torch.sqrt(2*torch.tensor(np.pi)*sigma**2)/n_atoms/normalization_eiglength_t

In [126]:
torch.save(normalization1, "./total_normalization_1.pt")

In [125]:
normalization1

tensor([0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0010, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0010, 0.0012, 0.0012, 0.0012, 0.0010, 0.0012, 0.0010, 0.0010, 0.0012,
        0.0010, 0.0008, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0010, 0.0012,
        0.0008, 0.0012, 0.0012, 0.0012, 0.0008, 0.0010, 0.0012, 0.0012, 0.0010,
        0.0008, 0.0010, 0.0010, 0.0008, 0.0010, 0.0012, 0.0008, 0.0010, 0.0010,
        0.0008, 0.0010, 0.0008, 0.0012, 0.0008, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 

In [128]:
torch.save(normalization, "./total_normalization_3.pt")
torch.save(total_eigen_energies, "./total_eigen_energies.pt")

In [100]:
from tqdm import tqdm

In [102]:
##Generate individual xdos, ldos
new_train_ldos = []

sigma = torch.tensor(0.3)
ndos = 778

emin = -24.5537 - 1.5
emax = 11.3464 + 1.5
x_dos = torch.linspace(emin, emax, 778)
for j, i in enumerate(tqdm(range(n_structures))):
    
    l_dos = torch.sum(torch.exp(-0.5*((x_dos- total_eigen_energies[i].view(-1,1))/sigma)**2), dim = 0)
    new_train_ldos.append(l_dos)

new_train_ldos = torch.vstack(new_train_ldos)
new_train_ldos = ((new_train_ldos.T * normalization).T)* 2

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 927/927 [01:53<00:00,  8.14it/s]


In [94]:
k_normalization

tensor([64, 64, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
        49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 70, 70, 70, 70, 70,
        70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
        70, 70, 70, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54,
        54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54,
        54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 72, 72, 72, 72,
        72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
        72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72,
        72, 72, 72, 72, 72, 72, 72, 72, 72, 72])

In [88]:
len(total_eigen_energies)

927

In [89]:
emin

tensor(-24.5537, dtype=torch.float64)

In [90]:
emax

tensor(11.3464, dtype=torch.float64)